#
# UFS/FFSv1/FFSv2 filesystem support
# Created by berte <behzaterte at yandex.com>
#
# SPDX-License-Identifier:   BSD 2-Clause License

obj-$(CONFIG_FS_UFS) := ffs.o ffs_common.o
obj-$(CONFIG_FS_UFS_WRITE) += ffs_write.o
